# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cheat-sheet',
                'doc_host': 'https://nesaboz.github.io',
                'git_url': 'https://github.com/nesaboz/cheat-sheet',
                'lib_path': 'cheat_sheet'},
  'syms': {'cheat_sheet.jupyter_nb_builder': {}}}
